### ISSUE TITLE
pekny pl

### ISSUE THREAD

**Issue by boi1216** [MinekCZ/BedWars#1]

**Comment by Tuvqlu** [comment]
hey! there isnt a description yet but i promise you it works great! It is a epic bw plugin with a scoreboard, generators, shop, and spectator! Get ready xd 


This is how you create
Do /bw admin create {arena}
then /bw admin setup

then /bw info

from there u can see everything u have to do

**Comment by boi1216** [comment]
@Tuvqlu check my github
